import Footer from '@/components/layout/footer/Footer'
import Header from '@/components/layout/header/Header'
import type { Metadata } from 'next'
import './globals.scss'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<body>
				<div className='flex flex-col min-h-full overflow-hidden'>
					<Header />
					<div className='flex-grow'>{children}</div>
					<Footer />
				</div>
			</body>
		</html>
	)
}
